export default {
  PageRouteData: [
    {
      title: 'ExampleBasic.',
      description: 'A simple example',
      page: 'ExampleBasic',
    },
    {
      title: 'ExampleCustomTabbar.',
      description: 'The example contains the usage of a custom tabbar',
      page: 'ExampleCustomTabbar',
    },
    {
      title: 'ExampleWithPullRefresh.',
      description: 'Make each Tab page allow pull-down refreshes',
      page: 'ExampleWithPullRefresh',
    },
    {
      title: 'ExampleWithTabViewPullRefresh.',
      description: 'Let the tabs component allow a drop-down refresh',
      page: 'ExampleWithTabViewPullRefresh',
    },
    {
      title: 'ExampleHeaderAnimated.',
      description: 'Get scrollTrans using the makeScrollTrans function',
      page: 'ExampleHeaderAnimated',
    },
    {
      title: 'ExampleCarouselHeader.',
      description: 'The header contains the Carousel component',
      page: 'ExampleCarouselHeader',
    },
  ],

  Page2Data: [
    {
      height: 100,
      text: '这里是测试文字',
      directory: 'left',
      imgSize: 80,
    },
    {
      height: 100,
      text: '这里是测试文字',
      directory: 'left',
      imgSize: 80,
    },
    {
      height: 100,
      text: '这里是测试文字',
      directory: 'right',
      imgSize: 80,
    },
    {
      height: 100,
      text: '这里是测试文字',
      directory: 'right',
      imgSize: 80,
    },
    {
      height: 100,
      text: '这里是测试文字',
      directory: 'right',
      imgSize: 80,
    },
    {
      height: 100,
      text: '这里是测试文字',
      directory: 'left',
      imgSize: 80,
    },
    {
      height: 100,
      text: '这里是测试文字',
      directory: 'left',
      imgSize: 80,
    },
    {
      height: 100,
      text: '这里是测试文字',
      directory: 'left',
      imgSize: 80,
    },
    {
      height: 100,
      text: '这里是测试文字',
      directory: 'right',
      imgSize: 80,
    },
    {
      height: 100,
      text: '这里是测试文字',
      directory: 'right',
      imgSize: 80,
    },
    {
      height: 100,
      text: '这里是测试文字',
      directory: 'left',
      imgSize: 80,
    },
    {
      height: 100,
      text: '这里是测试文字',
      directory: 'left',
      imgSize: 80,
    },
    {
      height: 100,
      text: '这里是测试文字',
      directory: 'left',
      imgSize: 80,
    },
    {
      height: 100,
      text: '这里是测试文字',
      directory: 'left',
      imgSize: 80,
    },
    {
      height: 100,
      text: '这里是测试文字',
      directory: 'left',
      imgSize: 80,
    },
    {
      height: 100,
      text: '这里是测试文字',
      directory: 'right',
      imgSize: 80,
    },
    {
      height: 100,
      text: '这里是测试文字',
      directory: 'right',
      imgSize: 80,
    },
    {
      height: 100,
      text: '这里是测试文字',
      directory: 'right',
      imgSize: 80,
    },
  ],

  Page3Data: [
    {
      title: '测试标题1',
      data: [
        '测试文本测试文本测试文本1',
        '测试文本测试文本测试文本2',
        '测试文本测试文本测试文本3',
        '测试文本测试文本测试文本4',
        '测试文本测试文本测试文本5',
        '测试文本测试文本测试文本6',
      ],
    },
    {
      title: '测试标题2',
      data: [
        '测试文本测试文本测试文本7',
        '测试文本测试文本测试文本8',
        '测试文本测试文本测试文本9',
        '测试文本测试文本测试文本10',
        '测试文本测试文本测试文本11',
        '测试文本测试文本测试文本12',
        '测试文本测试文本测试文本13',
        '测试文本测试文本测试文本14',
        '测试文本测试文本测试文本15',
        '测试文本测试文本测试文本16',
      ],
    },
    {
      title: '测试标题3',
      data: [
        '测试文本测试文本测试文本17',
        '测试文本测试文本测试文本18',
        '测试文本测试文本测试文本19',
        '测试文本测试文本测试文本20',
        '测试文本测试文本测试文本21',
        '测试文本测试文本测试文本22',
      ],
    },
    {
      title: '测试标题1',
      data: [
        '测试文本测试文本测试文本1',
        '测试文本测试文本测试文本2',
        '测试文本测试文本测试文本3',
        '测试文本测试文本测试文本4',
        '测试文本测试文本测试文本5',
        '测试文本测试文本测试文本6',
      ],
    },
    {
      title: '测试标题2',
      data: [
        '测试文本测试文本测试文本7',
        '测试文本测试文本测试文本8',
        '测试文本测试文本测试文本9',
        '测试文本测试文本测试文本10',
        '测试文本测试文本测试文本11',
        '测试文本测试文本测试文本12',
        '测试文本测试文本测试文本13',
        '测试文本测试文本测试文本14',
        '测试文本测试文本测试文本15',
        '测试文本测试文本测试文本16',
      ],
    },
    {
      title: '测试标题3',
      data: [
        '测试文本测试文本测试文本17',
        '测试文本测试文本测试文本18',
        '测试文本测试文本测试文本19',
        '测试文本测试文本测试文本20',
        '测试文本测试文本测试文本21',
        '测试文本测试文本测试文本22',
      ],
    },
    {
      title: '测试标题1',
      data: [
        '测试文本测试文本测试文本1',
        '测试文本测试文本测试文本2',
        '测试文本测试文本测试文本3',
        '测试文本测试文本测试文本4',
        '测试文本测试文本测试文本5',
        '测试文本测试文本测试文本6',
      ],
    },
    {
      title: '测试标题2',
      data: [
        '测试文本测试文本测试文本7',
        '测试文本测试文本测试文本8',
        '测试文本测试文本测试文本9',
        '测试文本测试文本测试文本10',
        '测试文本测试文本测试文本11',
        '测试文本测试文本测试文本12',
        '测试文本测试文本测试文本13',
        '测试文本测试文本测试文本14',
        '测试文本测试文本测试文本15',
        '测试文本测试文本测试文本16',
      ],
    },
    {
      title: '测试标题3',
      data: [
        '测试文本测试文本测试文本17',
        '测试文本测试文本测试文本18',
        '测试文本测试文本测试文本19',
        '测试文本测试文本测试文本20',
        '测试文本测试文本测试文本21',
        '测试文本测试文本测试文本22',
      ],
    },
    {
      title: '测试标题1',
      data: [
        '测试文本测试文本测试文本1',
        '测试文本测试文本测试文本2',
        '测试文本测试文本测试文本3',
        '测试文本测试文本测试文本4',
        '测试文本测试文本测试文本5',
        '测试文本测试文本测试文本6',
      ],
    },
    {
      title: '测试标题2',
      data: [
        '测试文本测试文本测试文本7',
        '测试文本测试文本测试文本8',
        '测试文本测试文本测试文本9',
        '测试文本测试文本测试文本10',
        '测试文本测试文本测试文本11',
        '测试文本测试文本测试文本12',
        '测试文本测试文本测试文本13',
        '测试文本测试文本测试文本14',
        '测试文本测试文本测试文本15',
        '测试文本测试文本测试文本16',
      ],
    },
    {
      title: '测试标题3',
      data: [
        '测试文本测试文本测试文本17',
        '测试文本测试文本测试文本18',
        '测试文本测试文本测试文本19',
        '测试文本测试文本测试文本20',
        '测试文本测试文本测试文本21',
        '测试文本测试文本测试文本22',
      ],
    },
  ],
};
